layout_spectrum: 0.59319
color:
  saturation: 0.3405018
  brandStrength: 0.9946237
  lightness: 0.5985663
  brandColors:
    - '#766F5B'
    - '#050B04'
    - '#E0D7D0'
    - '#C7B554'
    - '#4155B4'
  rhythmicContrast: 0.9862169
typography_spectrum: 0.9193549
name: Ceci Dean Interiors
